// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGOer3vMvhsUYY7im31EF11QOWf0HbrY',
    appId: '1:700757569335:web:1ae7eab1b7f6673b6a74b2',
    messagingSenderId: '700757569335',
    projectId: 'app-adota-fish',
    authDomain: 'app-adota-fish.firebaseapp.com',
    storageBucket: 'app-adota-fish.appspot.com',
    measurementId: 'G-EWHLEXCF37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV81wBf-GhPuZ6PNmyW2_LSK7tCVl29xg',
    appId: '1:700757569335:android:381cd08a9ab162cd6a74b2',
    messagingSenderId: '700757569335',
    projectId: 'app-adota-fish',
    storageBucket: 'app-adota-fish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnFobkHwhAcsHEzypsYHQKz8EzcZedR8',
    appId: '1:700757569335:ios:431c11ef8d9361816a74b2',
    messagingSenderId: '700757569335',
    projectId: 'app-adota-fish',
    storageBucket: 'app-adota-fish.appspot.com',
    iosClientId: '700757569335-a569nre2bn9k9f0e3d24h6bllpr8022q.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdotaFish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnFobkHwhAcsHEzypsYHQKz8EzcZedR8',
    appId: '1:700757569335:ios:431c11ef8d9361816a74b2',
    messagingSenderId: '700757569335',
    projectId: 'app-adota-fish',
    storageBucket: 'app-adota-fish.appspot.com',
    iosClientId: '700757569335-a569nre2bn9k9f0e3d24h6bllpr8022q.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdotaFish',
  );
}
